### ISSUE TITLE
Unit Tests: break into much smaller files

### ISSUE THREAD

**Issue by mikesherov** [jquery/esprima#1025]
We should take a page from espree here and break out the test files into much smaller pieces organized by the main language feature they are testing.

Right now it is unwieldily working with the giant file, and intimidating to newer contributors, like myself.

**Comment by ariya** [comment]
This depends on #1004.

**Comment by ariya** [comment]
There was the first step towards this (see [issue 590](https://code.google.com/p/esprima/issues/detail?id=509)), i.e. creating a fixture of input code and the baseline syntax and tokens.

At that time, it was limited only for test corpus because the test runner does not support it running on the browser. Once #1004 is there, it is a matter of expanding the same technique to the rest of the test suite.

**Comment by ariya** [comment]
Let's make sure that this can also tackle this old issue: https://code.google.com/p/esprima/issues/detail?id=544.
