### ISSUE TITLE
String Literal of "<\/script>" should not be rewritten to '</script>'

### ISSUE THREAD

**Issue by ameeshg** [jquery/esprima#1032]
A close script tag literal, i.e. `"<\/script>"` is rewritten to `'</script>'`. This is incorrect behavior because an unescaped close script tag ends javascript execution. 

The correct behavior would be to leave the backslash in the rewritten tag: `'<\/script>'`.

**Comment by fkling** [comment]
What do you mean by "rewritten"? Esprima creates an AST from the source code, it doesn't actually "write" anything. Are you talking about the `value` of the `Literal`?

![screen shot 2015-02-13 at 1 34 09 pm](https://cloud.githubusercontent.com/assets/179026/6195668/08180304-b385-11e4-8c73-e20e387adfe8.png)

`value` contains the literal content of the string. Because ``/`` is not an escape character, ``\/`` is converted to ``/``, just as defined in the [ECMAScript specification](http://www.ecma-international.org/ecma-262/5.1/#sec-7.8.4):

> - The CV of *SingleStringCharacter :: \ EscapeSequence* is the CV of the *EscapeSequence*.
> - [...]
> - The CV of *EscapeSequence :: CharacterEscapeSequence* is the CV of the *CharacterEscapeSequence*.
> - The CV of *CharacterEscapeSequence :: NonEscapeCharacter* is the CV of the *NonEscapeCharacter*.

This doesn't seem to be an issue with esprima.

**Comment by michaelficarra** [comment]
Nor is it an issue with escodegen, the tool you are probably using to codegen the AST. This a a problem with how *you* are encoding JavaScript in an HTML context. This issue has nothing to do with esprima. Also, use backticks to delimit code on Github and you won't have issues with talking about HTML.

**Comment by ikarienator** [comment]
@ameeshg Shall we close this? I think this issue doesn't apply here.

**Comment by ariya** [comment]
Closing this as Invalid.
