### ISSUE TITLE
API: Syntax delegator

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1113]
A sophisticated consumer ("power user") of Esprima might want to know and carry out a certain task when a particular event occurs. Among others, this could be when:

  * a syntax node is completed
  * a comment is encountered

This can be achieved if such a task is delegated to a specified delegator.

For a reference, see also [Delegation Pattern](http://best-practice-software-engineering.ifs.tuwien.ac.at/patterns/delegation.html).

**Comment by ariya** [comment]
Alternative A:

The delegator is supplied as the third argument to `parse`. Example code:

```js
var delegator = {
  processNode: function (node) {
    console.log('Yo, I found', node.type);
  }
};

esprima.parse(code, options, delegator);
```

Prior art: [Builder objects in Mozilla Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API#Builder_objects).

**Comment by ariya** [comment]
Alternative B:

The delegator is supplied as part of the options object. Example code:

```js
var delegator = {
  processNode: function (node) {
    console.log('Yo, I found', node.type);
  }
};

esprima.parse(code, { range: true, delegate: delegator });
```

**Comment by ariya** [comment]
@ikarienator Can you describe the issue with the cover grammar?

**Comment by ikarienator** [comment]
Cover grammars are syntactic placeholders introduced in ES6 that are parsed in one thing then reparsed to another structure. For example, `CoverInitializedName` defined in [12.2.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer). It is used as a part of `ObjectLiteral`, whereas if it actually shows up in `ObjectLiteral`, it is considered a syntax error ([12.2.5.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer-static-semantics-early-errors)). The reason to have this is that when an `ObjectLiteral` is parsed, it can be later converted into an `ObjectAssignmentPattern` or an `ObjectPattern`.

For example:
```es6
({a = 0, b, c, d})  // invalid grammar
({a = 0, b, c, d} = 3)  // valid assignment
({a = 0, b, c, d}) => 3  // valid arrow expression
```
Therefore, in order to report `a = 0` to be a valid `ConciseBindingProperty`, we have to wait until we finished the whole expression. This means that you must delay the reporting for arbitrary long. It also requires to delay it for arbitrary deep as well:

```es6
([[[[{a=0}]]]])  // invalid grammar
([[[[{a=0}]]]]) = 0  // valid assignment
([[[[{a=0}]]]]) => 0  // valid arrow expression
```

**Comment by ariya** [comment]
After the success of the token delegator (see #1332), I think I'm inclined to use the same model, e.g. the `delegate` parameter is just a simple function, hence **Alternative C** as illustrated by the following example:

```js
var list = [];
esprima.parse('answer = 42', {}, function (n) { list.push(n.type); });

console.log(list); // ['Identifier', 'Literal', 'AssignmentExpression', 'ExpressionStatement', 'Program']
```

**Comment by gibson042** [comment]
I still prefer the more explicit and less limiting **Alternative B**.
