### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by markelog** [jquery/esprima#1168]
Description will be added later

**Comment by michaelficarra** [comment]
Basic idea: allow sub-parsing functions to be overridden.

**Comment by ariya** [comment]
I'd like to close this for now and probably revisit it again in the future.

I believe that the most optimal approach to come up with a proper plugin API is by implementing various syntax extensions (see e.g. JSX support in #1467) and then abstracting it properly. This is more pragmatic than defining the plugin interface ahead of time and potentially struggling to use the interface properly.

**Comment by nowindowsowrking** [comment]
@ariya What is the plan for such an API? I noticed people choose Acorn over Esprima because of lack of this option? There doesn't exist many Acorn plugins, but they exist.

And also Babylon have a plugin API. I know Babylon API seem to be for internal usage. Not sure there. 
As far as I know Cherow also have a plugin API. A parameterized plugin system.
