### ISSUE TITLE
Why does esprima not uses parser generator?

### ISSUE THREAD

**Issue by golyshevd** [jquery/esprima#1170]
Pros:
* Easy modifications
* Easy to contribute
* Less source code

Cons:
* ?

I understand that it is not just for fun, so it is just question, really interesting

сс @markelog

**Comment by ariya** [comment]
That's the first thing I attempted to do back when I started working on it. Unfortunately, with all the corner cases of JavaScript syntax, we still need additional code to handle them. At some point, that additional code grow quite a lot, defeating the purpose of using the generator at the first place (think of all places where you need to account for a proper automatic semicolon insertion). This is with ES5, I can't imagine ES6.

There is a precedent for that. [SpiderMonkey](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey) and [V8](https://code.google.com/p/v8/) never started with generated parser to begin with. [JavaScriptCore](http://trac.webkit.org/wiki/JavaScriptCore) started using a bison-based grammar (inherited from [KJS](http://en.wikipedia.org/wiki/KJS_%28software%29)) but switched to hand-written parser due to the same problem.
