### ISSUE TITLE
Catch wrongly detected as keyword when tokenizing

### ISSUE THREAD

**Issue by mjesun** [jquery/esprima#1184]
Given the following code: `a.catch = 0;`, the token reporter will report the following elements:

```javascript
[
    {
        "type": "Identifier",
        "value": "a"
    },
    {
        "type": "Punctuator",
        "value": "."
    },
    {
        "type": "Keyword",
        "value": "catch"
    },
    {
        "type": "Punctuator",
        "value": "="
    },
    {
        "type": "Numeric",
        "value": "0"
    },
    {
        "type": "Punctuator",
        "value": ";"
    }
]
```

In the previous list, `catch` is recognized as a `Keyword`, while in the code is an `Identifier`. You can notice this by just changing `catch` to `catch_`, and then it will be correctly reported.

**Comment by michaelficarra** [comment]
... but it is a keyword. Remember that the tokeniser doesn't have parsing context.

**Comment by mjesun** [comment]
Does that mean that the `type` is exclusively inferred from a group of collections?

**Comment by michaelficarra** [comment]
I recommend reading up on [lexical analysis](https://en.wikipedia.org/wiki/Lexical_analysis). The tokeniser is context free and cannot tell if the "catch" lexeme is used as a keyword or in IdentifierName position. The reason esprima's tokeniser creates separate tokens for each keyword is to simplify the parser, allowing it to blindly accept identifiers in most positions without checking whether they are also a keyword. When parsing a static member access, a special provision allows keywords to also be accepted so that all IdentifierNames are allowed.

**Comment by mjesun** [comment]
I can perfectly assume that the tokenizer is not aware of the context; but what's the point of reporting a `type` if it can be wrong?

**Comment by michaelficarra** [comment]
It is not wrong. See [section 11.6.2.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-keywords). The ECMAScript spec has separate lexical and syntactic grammars (differentiated by using `::` and `:`, respectively). The lexical grammar for ECMAScript matches `catch` as a Keyword.

**Comment by mjesun** [comment]
Ok; I understand. Then you're right, it's not a bug. However, I think that it would provide much more value to have a tokenizer aware of the context, since it would make possible to use it as another strategy to make operations on top of the code: rather than going deep, just traversing linearly :)
