### ISSUE TITLE
npmignore test?

### ISSUE THREAD

**Issue by tmcw** [jquery/esprima#1191]
esprima's tests weigh about 896KB, and are always bundled in its npm package. There's [an npmignore](https://github.com/jquery/esprima/blob/master/.npmignore) but it only ignores parts of the test directory.

Would you be open to a PR that excludes the entire test directory, so the esprima bundle would be around 90% smaller? This would make a real difference for constantly-rebuilt test runners.

**Comment by ariya** [comment]
The only requirement is that we need to support those who want to `npm install` using `npat=true` (i.e. running the tests). I think the test runner needs to be modified so that it doesn't run anything if the test fixtures are not available.

**Comment by tmcw** [comment]
Gotcha: I [added a condition so that tests will run when `/test` is present and pass if not](d2a7a8fbefa530dbf425229e6c265210a9aa0c52).

**Comment by exogen** [comment]
Sorry to bring up an old issue, I know this is fixed in modern releases. It would be super nice if this was backported to old 1.x releases, e.g. by cutting a `1.2.6`, `1.1.2`, and `1.0.5` release (for packages depending on ranges with `~`). Lots of stuff throughout a large dependency tree still depends on these old versions and so is unfortunately bringing in that 896K. Yes, packages could upgrade their `esprima` dependency, but that is a widespread and potentially drawn out process. This would give people immediate and automatic relief from the large package. :)
