### ISSUE TITLE
`parseFunctionExpression` and `parseFunctionDeclaration` have duplicate code starting to be hard to maintain

### ISSUE THREAD

**Issue by ikarienator** [jquery/esprima#1210]
`parseFunctionExpression` and `parseFunctionDeclaration`  are almost identical. There has been a good reason to do that, but as the implementation become more and more complicated, we should start to abstract them.

**Comment by mikesherov** [comment]
@jasonlaster to attempt this one.

**Comment by jasonLaster** [comment]
Here's a quick gist with some progress.

https://gist.github.com/jasonLaster/007d7f27b9c1b2a86c73

I'm hoping that a couple shared functions like `parseFunctionIdentifer` ... can help encapsulate the shared logic. This current version is running into some shared state issues, but I'm pretty sure I can clean it up soon.

**Comment by ariya** [comment]
@jasonLaster Do you have a branch that I can look at? Usually it's easier to try out a branch that looking at a diff :-)

**Comment by jasonLaster** [comment]
Haha - I'll share something when I'm ready :) just wanted to let you know I've started doing some honest work (as opposed to messing w tests). Having a lot of fun.

**Comment by ariya** [comment]
After giving it more thought, I come to the conclusion that the unification is not really worth it (for an example of the unified version, look at PR #1243 from @jasonLaster). Due to the different handling of `yield`, there will be couple of conditionals/branches which we don't need desperately need, consider the functions are short anyway.

Thus, I'm inclined to resolve this without taking any action (aka,"as expected"). Thoughts? Comments?

**Comment by mikesherov** [comment]
I agree. The duplication is no longer serious enough. There are other opportunities for refactoring should we find it useful.
