### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by llafuente** [jquery/esprima#1236]
```js
(6 (5 * 7) + (8))
```
this example does't throw but node does: `TypeError: number is not a function`

**Comment by michaelficarra** [comment]
This is a valid ES5 program, but ES6 now restricts it. I'm not sure how esprima wants to handle those kinds of programs right now.

**Comment by ariya** [comment]
I think Esprima should treat this as an invalid code.

**Comment by michaelficarra** [comment]
Maybe tolerant mode should accept things that used to be valid in ES5 but are not longer valid in ES6 and beyond?

**Comment by mikesherov** [comment]
This would also be solved by language level flags too rather than relying on tolerant mode... But I support just treating it as invalid in esprima.

**Comment by ariya** [comment]
Looking at V8 source code, this error message is denoted as `called_non_callable`. However, AFAICS it is a run-time error for V8, its parser does not attempt to detect (in the given example) that the callee is just a literal.

The same goes for SpiderMonkey (from Mozilla). In fact, its `Reflect.parse` happily consumes the example code. It is not until SpiderMonkey tries to execute the code that it will throw a similar error message.

From the latest ECMA-262 production grammar, I can't see any production that will be invalidated by the example. There does not seem to be any related early error, either. Of course, I may miss something there.

Also, I can't find a JavaScript-based parser that flags this case as an error (not even the sophisticated transpiler such as Traceur or TypeScript). Should we just relegate this as a task for a static analyzer (as a matter of fact, JSHint complains about it) rather than the responsibility of a parser?

**Comment by michaelficarra** [comment]
@ariya Yeah, that's entirely a runtime error. Not sure what I was thinking 6 months ago.
