### ISSUE TITLE
Esprima fails to parse a fat arrow function in some contexts

### ISSUE THREAD

**Issue by gotwarlost** [jquery/esprima#1269]
Ref: https://github.com/gotwarlost/istanbul/issues/418

This works: http://bit.ly/1SIuqok

This fails: http://bit.ly/1hhLtg2

**Comment by michaelficarra** [comment]
ArrowFunction is an AssignmentExpression. You would need to parenthesise the arrow to allow it as a subexpression of a LogicalORExpression: `a || () => 0`. For example, you wouldn't expect `a || b = c` to parse. Because YieldExpression is also an AssignmentExpression, you should also be careful using it in high-precedence positions: `a || yield` must be written as `a || (yield)`.

**Comment by michaelficarra** [comment]
I see that babel accepts these non-programs, so I've opened an issue with them here: https://github.com/babel/babel/issues/2154

**Comment by ariya** [comment]
As @michaelficarra wrote, this is the expected behavior. We will resolve this "as expected".
