### ISSUE TITLE
comments missing bug in empty BlockStatement

### ISSUE THREAD

**Issue by fishbar** [jquery/esprima#1328]
early time, when es6 multiline feature is not available in node.js,  we always using `module:multiline` to write multiline strings(especially  sql),  it make code easy to read, code like:
```
var multiline = require('multiline');

var sql_xxxx = multiline(function () {
/*
SELECT
    columnes ...
FROM
    some_table
WHERE
    ..........
*/
});
```

but when we write testcase using  istanbul (which is writting in `esprima`, `escodegen`),  the comments in the anonymous function will be ate by esprima.

though esprima later support `attachComment` ( `leadingComments` and `tralingComments`) , but still missing the comments in the empty `BlockStatement`

**Comment by ariya** [comment]
The comment attachment functionality was originally devised to detect an annotation to e.g. a function (in the style of JSDoc or other similar documentation tool), hence why it's missing the feature to collect an "orphan comment" like the above example.

It's always slippery slope to continue to support cases like this since ideally it's tackled by a true concrete syntax tree (CST). However, for (1) the sake of completeness and (2) such orphaned comments are rare, I think it's fine to venture the addition of `innerComments`.

(At some point thought, perhaps in the 3.x series, this whole comment attachment business needs some serious reconsideration)
