### ISSUE TITLE
Esprima 2.7.0 changes the behavior of `esprima.tokenize(comment=true)`

### ISSUE THREAD

**Issue by kaelzhang** [jquery/esprima#1351]
Esprima `2.7.0` changes the behavior of `esprima.tokenize(comment=true)`, so it should bump version number to `3.0.0`

```js
esprima.tokenize('//top\n{"a":1}', {comment: true});
```

The output of esprima 2.6.0 is:

```js
[ { type: 'Punctuator', value: '{' },
  { type: 'String', value: '"a"' },
  { type: 'Punctuator', value: ':' },
  { type: 'Numeric', value: '1' },
  { type: 'Punctuator', value: '}' },
  comments: [ { type: 'Line', value: 'top' } ] ]
```

While esprima 2.7.0:

```js
[ { type: 'LineComment', value: 'top' },
  { type: 'Punctuator', value: '{' },
  { type: 'String', value: '"a"' },
  { type: 'Punctuator', value: ':' },
  { type: 'Numeric', value: '1' },
  { type: 'Punctuator', value: '}' } ]
```

**Comment by ariya** [comment]
The reason I did it that way is because I think it was an egregious mistake to treat comments in the pure tokenizer the same way as in the parser. After all, the tokenizer is expected to produce a linear stream of tokens (optionally including the line and block comments).

2.7's tokenizer is pretty much the same as 2.6 (unless you want to use the new delegator feature), so it should be safe to stay with 2.6. @kaelzhang I'll be willing to take a look at node-comment-json to propose a pull request that make it work with 2.7. Let me know!

**Comment by ariya** [comment]
This is now resolved within node-comment-json itself (see https://github.com/kaelzhang/node-json-parser/pull/7).
