### ISSUE TITLE
Class Literal#value should allow boolean and number types?

### ISSUE THREAD

**Issue by Nathan-Wall** [jquery/esprima#1471]
The `value` property on class `Literal` is currently [typed as `string` only](https://github.com/jquery/esprima/blob/master/src/nodes.ts#L447). Shouldn't it be `boolean|number|string`?

**Comment by Nathan-Wall** [comment]
I *think* the reason the compiler doesn't currently complain is because it's [assigned from `token.value`](https://github.com/jquery/esprima/blob/master/src/parser.ts#L603) where `token` is of type `any`.

**Comment by ariya** [comment]
Thanks for the notice!

You're right than the type information is lost due to the current state of the code. In the very near future, I plan to add more type annotation, in particular as part of the refactoring to simplify the internal token structure (from Scanner) which should be different than a public/external token structure (from Tokenizer). Meanwhile, as a stop gap measure, I'll manually enumerate more types for the `value`.

BTW, out of curiosity, did you discover this by looking at the code or with a certain tool?

**Comment by Nathan-Wall** [comment]
> BTW, out of curiosity, did you discover this by looking at the code or with a certain tool?

I'm using Esprima as the base of the parser for a JavaScript-like language I'm working on. I'm making a lot of modifications to Esprima, so I encounter things like this from time to time. In this case, I started creating a new `Literal` node from a value which was known by TypeScript to be a number, so it complained.

PS: Thanks for all the work you do on Esprima! I've been using it for 3 years now on various projects, and it's been super helpful. 3 years ago it was fun to work with, but all of the refactoring, breaking things into modules and adding type annotations, you've been doing recently have made it even easier to work with.

**Comment by ariya** [comment]
Good to know that Esprima is useful for you @Nathan-Wall! There will be some more small-scale refactoring (after 3.0) which hopefully make everything easier to work with. Feedback is of course always welcomed!
