### ISSUE TITLE
jspm support in package.json?

### ISSUE THREAD

**Issue by hmalphettes** [jquery/esprima#1486]
Hi!

Currently when we install esprima with jspm to be consumed by a browser, we end-up installing the schims for the `fs` module and the `process` module.

There are various ways to override this behavior.
The easiest one consists of adding a jspm element to the package.json.

Is this something worth a pull request or would you rather keep the jspm specifics outside of the `esprima` repository?

Thanks for your attention!

**Comment by hmalphettes** [comment]
Currently I am using my fork to achieve this:
https://github.com/sutoiku/esprima/commit/1aac5a884d1e324c7c793d5d5d819c207a8a51d7
```
jspm i esprima=github:sutoiku/esprima@2.7.2.j
```
I hope this helps.

**Comment by ariya** [comment]
If the change is only adding a simple `jspm` property into the `scripts` section, I'm find with that.
Please go ahead and create a pull request.

**Comment by michaelficarra** [comment]
esprima shouldn't be using `fs` or `process` to begin with.

**Comment by hzoo** [comment]
I think it's since the bin files use it - https://github.com/jquery/esprima/blob/master/package.json#L6-L14?

**Comment by michaelficarra** [comment]
Consumers of esprima as a library shouldn't need the files in `bin`.

**Comment by hmalphettes** [comment]
@michaelficarra correct. We don't need `fs` or `process`. jspm thinks they are required.
This patch explicitly tells jspm that esprima does not have any dependencies as far as it is concerned.

**Comment by michaelficarra** [comment]
@hmalphettes Why does jspm think they are required?

**Comment by ariya** [comment]
@hmalphettes Shouldn't we fix jspm so that the lack of `jspm` entry indicates no dependency?

**Comment by hmalphettes** [comment]
@michaelficarra @ariya I agree with you guys but we are going deep into what logic jspm is using when parsing package.json and javascript code.

My feeling is we are unlikely to change that logic.

I have asked for the jspm experts to help us decide.

Thanks again for your attention!

**Comment by guybedford** [comment]
Thanks for pinging me in on this, it's great to see esprima open to supporting these types of configurations.

Well it sounds like you're all completely on top of the details here - yes exactly, jspm will read all the files in the package to see what Node native dependencies are needed, and then install the browserify libs of those into the local project. So we need to tell jspm to not do this.

There are three ways of doing this -

1. Exactly as in the PR - `{ jspm: { dependencies: {} }}`
2. Removing the `bin` folder from the files of the package - `{ jspm: { files: ['dist/esprima.js'] }}`, although there may be future compatibility concerns here if and when jspm one day supports bins.
3.  Disabling the entire NodeJS conversion process since it seems like `dist/esprima.js` is actually a UMD anyway and not expecting NodeJS conventions at all. This can be done with `{ jspm: {  jspmNodeConversion: false  } }`.

(3) is probably the advisable route here, and it's always best to have these configurations in the original package.json where possible. For older versions of esprima already published an override in the jspm registry will probably still be necessary though.

**Comment by michaelficarra** [comment]
I'm pretty firmly against adding any package manager specific fields to `package.json`. Is there any *generally useful* metainfo we can add instead?

**Comment by mikesherov** [comment]
@guybedford, would it be possible to detect UMD usage in the `main` file and ignore the node specific path and therefore automatically conclude that Esprima is not node dependent?

This, if possible, seems like it would obviate the need for jspm specific config in Esprima's package.json file. Thoughts?

**Comment by hmalphettes** [comment]
@michaelficarra All done from the jspm's registry side of things.
My personal opinion about not adding to package.json something related to another specific package manager: I agree with you.

In the past esprima was supporting components and when it was removed jspm was mentioned as the potential replacement: https://github.com/jquery/esprima/issues/1207. That was the reason I opened this issue here.

Thanks for the clarification!

Many thanks again for your attention.
