### ISSUE TITLE
Distinguish between Modules and Scripts 

### ISSUE THREAD

**Issue by CMatias** [jquery/esprima#1492]
Not sure if this is the correct place to ask this so sorry in advance.

In the online parsing page whenever and export or import keyword is introduced the sourceType changes from script to module. I need to mimic this behavior. Is there anyway to do it without the use of try/catch or making a first pass considering the code a module and looking for imports and exports? I'm asking since I need to be able to parse any type of Javascript file without previous knowledge of it.

**Comment by CMatias** [comment]
Already found the piece of code which does it: 

```
function deduceSourceType(code) {
    var type = 'module';

    try {
        esprima.parse(code, { sourceType: 'script' });
        type = 'script';
    } catch (e) {
    }

    return type;
}
```

**Comment by mikesherov** [comment]
the only bulletproof method is knowing beforehand. The following is both a valid module and a valid script:

```
var a = function() {};
a.name = 'name';
window.a = a;
```

If parsed and executed as a problem, this example throws, because assigning to function.name is disallowed in strict mode, which all modules are.

However, if you're ignoring the ambiguous case, parsing as a strict first, and then parsing as a module if parsing script fails is the only other way of doing it.

I hope this helps, and yes, asking on the mailing list would've been more appropriate than the bug tracker, so please use that next time.
