### ISSUE TITLE
trailing comment clipped by comma in object literal

### ISSUE THREAD

**Issue by shenanigans** [jquery/esprima#1521]
When commenting properties of an Object literal, any comment appearing after a property's comma becomes a `leadingComment` of the next property rather than a `trailingComment` of the current property. I think such a comment should be a `trailingComment` as long as it begins on the same line on which the expression it trails ends.

The example input:
```javascript
var obj = {
    foo: 1, // one
    bar: 2  // two
};
```

In the parse output, we find that `bar` has been given both comments.
```json
{
    "type": "Property",
    "key": {
        "type": "Identifier",
        "name": "bar"
    },
    "leadingComments": [
        {
            "type": "Line",
            "value": " one"
        }
    ],
    "trailingComments": [
        {
            "type": "Line",
            "value": " two"
        }
    ]
}
```

If we add the acceptable quirk of a trailing comma in the input, as such...
```javascript
var obj = {
    foo: 1, // one
    bar: 2, // two
};
```

Now the second comment disappears entirely, only to be found in the `comments` property of the root node. If a third property is added...
```javascript
var obj = {
    foo: 1, // one
    bar: 2, // two
    baz: 3
};
```
The second comment is assigned to `baz` as a `leadingComment`.

**Comment by ariya** [comment]
The current behavior can be explained by the way the attaching process works: (1) It only pays attention to the zero-based range of the node where the comment is supposed to be attached, hence it doesn't realize the same-line positions between the comment and the node (2) There is an inherent limitation where a comment is orphan since it exists in the space where there is associated node.

It is unlikely that we change the way the comment is attached. There are dependent tools that might break because of that. Yet, everyone wants to have their own flavor of comment attachment. This is why in the upcoming version, it is impossible to "invent" your way of processing and attaching comment. There is no documentation on this yet, but feel free to look at this test for some ideas: https://github.com/jquery/esprima/blob/master/test/api-tests.js#L387.

**Comment by shenanigans** [comment]
Neat, ok. I understand where you're coming from regarding compatibility with existing code. I myself worked around the behavior in a way that would break if it changed. Still, I'll probably migrate to the custom comment processor when it goes live just 'cause it'll be more legible and "correct" that way.

**Comment by ariya** [comment]
Acknowledged. This is why moving forward, I think we want to take the stance of "please, attach comments the way you like it". The current way of attaching comment is not going to be more endorsed than a customized one (via that delegate approach), it's merely a _legacy_ comment handler for compatibility reason.
