### ISSUE TITLE
Throws on valid syntax after the specs

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1632]
@ariya Esprima are throwing syntax error on this combos, but they are all valid after the specs. I was using the online parser, so maybe changed in a newer version? I noticed the online parser is an old version.

```js

//-  Unexpected token [
var [a, ...[b, c]] = d

//- Illegal return statement
return {} / 2

//- Illegal return statement
return\n{}\n/foo/

//-  Unexpected token [
({ x(...[ a, b ]){} })
```

**Comment by ariya** [comment]
Thanks for the report @nowindowsowrking!

For the first and the last, I think it's known problem. There must be an issue filed already, I have to look it up.

The two cases with `return` are not valid. Return statement must exist within a function body. You may have the impression that it is valid due to Node.js running any code by wrapping it with a function.

**Comment by nowindowsowrking** [comment]
@ariya I also found that this combos is throwing, and they should not do that

```js
//|  Invalid regular expression
/[\\uD834\\uDF06-\\uD834\\uDF08a-z]/u
```

**Comment by nowindowsowrking** [comment]
Combos listed here mostly throws: `Error: Line 1: Invalid regular expression`

**Comment by ariya** [comment]
This is now spawned as a more elaborated test case, see 1681.
