### ISSUE TITLE
Arrow function expressions followed by regular expressions are not parsed correctly

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1642]
```js
//| 
var foo = function() { return bar }
/regex/.test('baz');
```

**Comment by ariya** [comment]
Please describe:
* what is the actual output?
* what is the expected output according to the specification?

**Comment by nowindowsowrking** [comment]
@ariya Actual output is that this combinations throws, and they should get parsed.

Expected output

```js
{ type: 'Program',
  body:
   [ { type: 'ExpressionStatement',
       expression: [Object],
  sourceType: 'script',
}
```
Actual output

`Error: Line 3: Unexpected token .`

**Note! I used my own parser to get correct result to show expected result*

**Comment by ariya** [comment]
Hmm, it's confusing because there is no arrow function expression, only a regular function expression. And since this is an expression, it is expected that it does not _terminate_ with a newline, thus making it equivalent to this one-liner (which is invalid):
```js
var foo = function() { return bar } /regex/.test('baz');
```

In fact, if you try to use Node.js/V8 for each example (2-line and 1-line), you'll see an error:
```
SyntaxError: Unexpected token .
```

**Comment by nowindowsowrking** [comment]
@ariya I agree in this. I tried this now with 4 different parsers, and if I "tweak" the above it will parse. But as it is now, yes it throws an syntax error as you mentioned. So I close this.
