### ISSUE TITLE
It would be great if the test suite could have its own repo

### ISSUE THREAD

**Issue by icefapper** [jquery/esprima#1698]
Hello;
also,
Merry Christmas!

by the way,
The test suite that esprima is using is very suitable for stress testing any other ECMAScript parser.
Also the fact that it has ready-to-use AST jsons means parser authors will not have to do all the hard work of adapting the tc39 test suite into the parser they have made -- all they have to do is use Esprima's tests; the only thing they might need is possibly an "adjuster" hook to convert the ASTs their respective parsers generate into an esprima compatible AST; currently, the tests come as an integrated part of Esprima, but for those who only need the test suite, that would be unnecessary, even though trivial. 
Additionally, having an independent repo for the test suite means the test suite will be under a bigger spotlight, whcih gives it a better chance to remain free of bugs.

**Comment by ariya** [comment]
Thanks for the suggestion!

The closest to this is https://github.com/tc39/test262.

In general, splitting the test suite to its own repo will increase the maintenance burden with no significant benefit. _If_ there would have been an external significant contribution to the test suite, we may consider it. Otherwise, it is an inconvenient exercise with dubious advantages.
