### ISSUE TITLE
Anonymous function doesn't parse

### ISSUE THREAD

**Issue by whisperstars** [jquery/esprima#1701]
Wrong parsing an anonymous functions.

`var esprima = require('esprima');
var program = '{a: function () {}}';
console.log(esprima.parse(program));`
returns
> Error: Line 1: Unexpected token (

In backbone apps it will be a great feature

**Comment by mikesherov** [comment]
Thanks for contributing! Esprima is exhibiting the correct behavior here. As weird as it may seem, `{ a: function () {}}` is considered a block statement with a labeled statement inside of it. The labeled statement is `function () {}` which is a syntax error.

In order to get any parser to interpret this as an object instead of a block statement, try adding a variable declaration like `let a = ` in front.

Thanks again!

**Comment by whisperstars** [comment]
Nice catch. thanks!
I'm a little misunderstood of processing code

**Comment by tomchadwin** [comment]
I'm still struggling with this. My code:

```javascript
a = new b({
    c: function (x) {
        return x;
    },
});
```

How can I make this parse, without fully defining my function instead of calling it anonymously?
