### ISSUE TITLE
`let` is sometimes a plain identifier

### ISSUE THREAD

**Issue by icefapper** [jquery/esprima#1724]
Hello
let is not always a keyword, but the tokenizer always marks it as such; for example, in `var let;` it is actually an identifier, but the token returned is given the type `Keyword`. not a huge issue, but worth mentioning.

**Comment by mikesherov** [comment]
Thanks for contributing! As far as the let `token` goes, since the tokenizer attempts to be context free, it is always a keyword. Tokens in general, except for cases like `}` to disamibiguate the end of a template expression from objects (which can be determined with a simple stack), just represent what type the token is without consideration of higher level syntactic structures. That's what the AST is for.

With that said, this is a wontfix, but thanks again for reporting.
