### ISSUE TITLE
[Question] Template literal improvements

### ISSUE THREAD

**Issue by nowindowsowrking** [jquery/esprima#1791]
@ariya @mikesherov I was wondering what is the purpose with the `curlyStack` in the scanner class? 

Esprima looses performance with it, and there are some reduntant checks that is not needed as far as I could figure out.

I can't make a PR from my computer (*work related*), but with a few single steps and you can get rid of it.
But you only need to change `parseTemplateElement()` and `parseTemplateLiteral()` into this and you can remove `curlyStack`

```js
 parseTemplateElement(): Node.TemplateElement {
        this.scanner.index = this.lookahead.start;
        const node = this.createNode();
	      // we hit a '}', and need to re-scan the template from previous position
        const token = this.scanner.scanTemplate();
           this.nextToken();
        const raw = token.value as string;
        const cooked = token.cooked as string;

        return this.finalize(node, new Node.TemplateElement({ raw, cooked }, token.tail as boolean));
    }

parseTemplateLiteral(): Node.TemplateLiteral {
        const node = this.createNode();

        const expressions: Node.Expression[] = [];
        const quasis: Node.TemplateElement[] = [];

        let quasi = this.parseTemplateHead();
        quasis.push(quasi);
        while (!quasi.tail) {
            expressions.push(this.parseExpression());
            // Catch unterminated template strinc. E.g. `hello ${10;test`
            if (this.lookahead.value !== '}') {
                this.throwUnexpectedToken(); // TODO! Add error msg saying "Unterminated template" etc
            }
            quasi = this.parseTemplateElement();
            quasis.push(quasi);
        }

        return this.finalize(node, new Node.TemplateLiteral(quasis, expressions));
    }
```
I tested this locale, and it all works.

**Comment by nowindowsowrking** [comment]
I also found issues with unicodes etc. Both for template literals and string literals. I can cut&paste a solution for that as well soon I have created one.

**Comment by mikesherov** [comment]
Thanks for contributing. 

Esprima has `tokenize`, needs a stack to differentiate`}` between a punctuator and the end of a template literal at the token level. I also believe it needs this for `parse` too to produce the correct token types, not just the correct AST nodes, for when token attachment is used.

If you can get all the tests to pass as is without curlyStack, and `tokenize()` produces the correct nested tokens, and performance improves, a PR is welcome, but go ahead and do `git log -S curlyStack` to see the commits that introduced it and what bugs it fixed.

In the meantime, I'm going to close this issue. Thanks again!

**Comment by nowindowsowrking** [comment]
@mikesherov Ok. Only issue ticket I found was this one https://github.com/jquery/esprima/issues/1143 
You was the one who created a solution for it.

However with my solutin above. All Esprima tests pass, and also the mentioned issue are still fixed.

Sadly due to my daily work I can't do any PR. But at least you know now there exist an alternative solution for curlyStack.

**Comment by mikesherov** [comment]
I'm not sure how there could be a solution involving only `parse*` methods when `tokenize` doesn't use them?

Perhaps the test suite needs to be strengthened in this case?

**Comment by nowindowsowrking** [comment]
Good catch! There are no tokenize tests covering this so it should have been strengthened. And you are right. I ran into an issue with this solution for tokenization when I tested this. I will find a fix shortly

**Comment by nowindowsowrking** [comment]
@mikesherov Easy fix!  In tokenize class. In the constructor you have to add a `inTemplate: boolean` and set it to a falsy value by default. Similar code exist already in that class. 

After this line   `let token = startRegex ? this.scanner.scanRegExp() : this.scanner.lex();` you add

```js
                // mark if this is inside an template literal
                if (token.type === Token.Template) {
                  this.inTemplate = true;
                }
                 // we are inside an template literal and found a '}', go back to prev index pos
                if (this.inTemplate && token.type === Token.Punctuator && token.value === '}') {
                  this.scanner.index = token.start;
                  token = this.scanner.scanTemplate();
                }
```

However. My original plan was to try to fix all errors on Esprima mentioned in the issue tickets, but I see now that is an complex task because the way the code base are. Can't be solved without major rewrites.

**Comment by mikesherov** [comment]
Can't be solved with simple boolean because unlike regex you can nest objects inside templates inside objects inside templates... you get the point. You can pop out of a template into a template.

The best way to improve the Esprima code base is the way we've suggested to you several times: find issues, file individual bugs, then submit PRs fixing them.

**Comment by mikesherov** [comment]
And so, the easiest way to prove you have a better solution for tokenizing nested template literals is to add a test for tokenizing template literals that includes deep nesting, then make your change, then see that tests still pass, then run the benchmark suite before and before and show how it's more performant, and then submit a PR with the performance results in the PR description.

It's not that I don't believe you, but at this point I don't think it'll help, and I could be easily convinced otherwise with a PR proving it.

The fact that the scanner class for bugs for octals or line terminators has nothing to with your ability to fix the performance bug described in this issue.

**Comment by nowindowsowrking** [comment]
@mikesherov Sorry for late reply on this. I ran a few complex tests locale with my current solution and they both works as expected:

```js
esprima.tokenize('`url(${require(`../../assets/${edge.node.name.toLowerCase()}.png`)}) center no-repeat`');
esprima.tokenize('`${a}${b}`');
```
But I will come back to this later on.

**Comment by mikesherov** [comment]
@nowindowsowrking have you tried 

```
esprima.tokenize('`${{a:`${{b:{}}}`}}`');
```

If that still works, then I'm convinced! Let me know, thanks! And thanks again for digging in.

**Comment by ariya** [comment]
The scanner is not designed so that you rewind it back. Doing `this.scanner.index = token.start` is pretty dangerous. I don't recall every possible impact it may have, but reviewing and tracking that down will be time consuming.

Unless this has a demonstrable speed-up (beyond just microbenchmars), I would be quite hesitant going down that path.

**Comment by nowindowsowrking** [comment]
@mikesherov I started too look into it again now, and tried it and it works, but I discovered a lot of other strange things. I can't put words on it yet except there is an regression issue between the version of Esprima on NPM and current source in the Master branch when it comes to tokenization regex. What worked before, does not work anymore.  
@ariya I noticed the scanner issues if that was what you were thinking of? However if you look at the TS scanner you see how they do it with templates. I picked up the idea from there. If you look at that source code you will notice Esprima does the same thing with regexp.

I also noticed that the tokenizer class could be simplified, and that would probably solve some of the open issues. Have you read [this one](https://github.com/sweet-js/sweet.js/wiki/design) ?

**Comment by nowindowsowrking** [comment]
@mikesherov @ariya If you take a look at the Shift parser you will notice that they also rewind back the template literal. As [seen here](https://github.com/shapesecurity/shift-parser-js/blob/es2016/src/parser.js#L1533-L1537)

**Comment by mikesherov** [comment]
@nowindowsowrking, same as I always say... instead of trying to put things into words or conjecturing about what might solve what, open a pull request with the changes, demonstrate the bug that is being fixed, and demonstrate the benchmark that is being improved.

As per what Shift does, once again, that is in the context of parsing, not of tokenization. If you could demonstrate with a PR that this works for tokenize, we can stop going around in circles and start actually fixing things.

**Comment by ariya** [comment]
@nowindowsowrking It's probably better if you create a diff/patch or something. Unfortunately, I am having a hard time following your narrative. For example, what to do with the use of `curlyStack` inside the primary `lex()` function is not clear from your description.

Also, I'm also not sure what you mean by the tokenizer simplification. The link that you gave is the description of the algorithm that is already implemented by the tokenizer more than 4 years ago, see commit 2e818265.
(Again, for a different topic unrelated to the original discussion on template literal, it's better to open a new issue or even better, start a new thread in the mailing-list).
