### ISSUE TITLE
esprima.tokenize('/') throws an error

### ISSUE THREAD

**Issue by vezwork** [jquery/esprima#1895]
using esprima@4.0.0

### Steps to reproduce
```js
esprima.tokenize('/')
```

### Expected output
```
[{type: "Punctuator", value: "/"}]
```

### Actual output
```
ERROR esprima.js:5000 {
  description: "Invalid regular expression: missing /"
  index: 1
  lineNumber: 1
  column: 2
}
```

**Comment by nowindowsowrking** [comment]
@vezwork Clone this repo. @ariya fixed this issue in a earlier PR. And as you can see of [this](https://github.com/jquery/esprima/blob/df749a7fd319a72beb46d28c612da6c8497e7488/test/fixtures/tokenize/single_slash.js) test case. The issue is solved.
The only thing is that this hasn't been published to NPM. Something I doubt while happen before march 2018 when Esprima 5.0 are released to the public.

**Comment by vezwork** [comment]
@nowindowsowrking thank you very much! I suppose I should have tried that first.

**Comment by ariya** [comment]
Hi @vezwork, as @nowindowsowrking wrote above, this is a duplicate #1772.
