### ISSUE TITLE
Unexpected token ILLEGAL with function literal in template literal

### ISSUE THREAD

**Issue by evanw** [jquery/esprima#1991]
### Steps to reproduce

Attempting to parse this code causes an error:

```js
`${function() { let {x} = y; }}`
```

This is a reduced test case from a real app. We were using a string like this to create the source code for a web worker.

### Expected output

This should be able to parse fine. The code parses fine with other parsers and works fine in the Chrome Developer Tools console.

### Actual output

I get this instead:

```
Error: Line 1: Unexpected token ILLEGAL
```

**Comment by JosephPecoraro** [comment]
This appears to be because scanner `saveState` and `restoreState` do not save and restore the `curlyStack` array.

So when parsing in `isLexicalDeclaration`:

```ts
isLexicalDeclaration() {
    const state = this.scanner.saveState();
    this.scanner.scanComments();
    const next = this.scanner.lex();
    this.scanner.restoreState(state);
    ...
}
```

This `lex` can add a curly brace to the stack, and when the lex happens again re-adds a curly brace to the stack.

Making `saveState` and `restoreState` hold a copy of `curlyStack` gets this to parse properly.
